apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "giantmuseum.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "giantmuseum.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "giantmuseum.name" . }}
    spec:
      containers:
        - name: giantmuseum
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000