apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "giantmuseumweb.fullname" . }}
spec:
  rules:
    - host: giantmuseumweb.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "giantmuseumweb.fullname" .}}
                port:
                  number: 3000