apiVersion: v1
kind: Service
metadata:
  name: {{ include "giantmuseumweb.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    targetPort: 3000
  selector:
    app {{ include "giantmuseumweb.name" . }}