apiVersion: v1
kind: Service
metadata:
  name: giantmuseumweb-service
  namespace: giantmuseumweb
spec:
  selector:
    app: giantmuseumweb
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
